# Generated by Django 3.2.8 on 2021-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=255)),
                ('P_details', models.CharField(max_length=255)),
                ('P_qty', models.IntegerField()),
                ('P_price', models.IntegerField()),
            ],
        ),
    ]
